replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "mirrorfall/gobot"
  tag: "v1.0.4-60d4d98"
  arch: amd64
  os: linux
secret:
  name: "gobot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
imagePullSecrets:
  - name: regcred
