replicaCount: 1
image:
  repository: mirrorfall
  tag: "1.0.4-880d0b1"
  arch: amd64
  os: linux
secret:
  name: "gobot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
imagePullSecrets:
  - name: regcred
